swagger: "2.0"
info:
  version: 1.0.0
  title: demo-rest-nodeservice
  description: My cool REST service
basePath: /api/v1
tags:
  - name: People
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json


definitions:
  PersonBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        example: Joe Schmoe
      phone:
        type: string
        example: '(403) 867-5309'

paths:
  /people:
    get:
      tags:
        - People
      description: Fetch all people
      responses:
        200:
          description: Returns all people
    post:
      tags:
        - People
      description: Create a new example
      parameters:
        - name: example
          in: body
          description: an example
          required: true
          schema: 
            $ref: "#/definitions/PersonBody"
      responses:
        200:
          description: Returns all people

  /people/{id}:
    get:
      tags:
        - People
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the example to retrieve
          type: integer
      responses:
        200:
          description: Return the example with the specified id
        404:
          description: Example not found

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification