swagger: "2.0"
info:
  version: 1.0.0
  title: demo-rest-nodeservice
  description: My cool REST service
basePath: /api/v1
tags:
  - name: People
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json


definitions:
  PersonBody:
    type: object
    title: person
    required:
      - firstname
      - lastname
    properties:
      firstname:
        type: string
        example: Joe
      lastname:
        type: string
        example: Schmoe
      # phone:
      #   type: string
      #   example: '(403) 867-5309'

paths:
  /people:
    get:
      tags:
        - People
      description: Fetch all people
      responses:
        200:
          description: Returns all people
    post:
      tags:
        - People
      description: Create a new person
      parameters:
        - name: person
          in: body
          description: a person
          required: true
          schema: 
            $ref: "#/definitions/PersonBody"
      responses:
        201:
          description: Returns created person
        400:
          description: Bad request

  /people/{id}:
    get:
      tags:
        - People
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the person to retrieve
          type: integer
      responses:
        200:
          description: Return the person with the specified id
        404:
          description: Person not found

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification