apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  clusterIP: None # commented
  # type: NodePort  # added
  ports:
  - port: 9042
    # nodePort: 30001 # added
  selector:
    app: cassandra


# spec:
#   type: NodePort
#   ports:
#     - port: 80
#       nodePort: 30080
#   selector:
#     app: wordpress



# A no longer headless service to create DNS records
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: broker
#   namespace: kafka
# spec:
#   type: NodePort
#   ports:
#   - port: 9092
#   - nodePort: 30092
#   # [podname].broker.kafka.svc.cluster.local
#   selector:
#     app: kafka