---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: people-service
  namespace: default
  selfLink: "/apis/extensions/v1beta1/namespaces/default/deployments/people-service"
  labels:
    run: people-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: people-service
  template:
    metadata:
      creationTimestamp: 
      labels:
        run: people-service
    spec:
      containers:
      - name: people-service
        image: people-service:v1
        ports:
        - containerPort: 3000
          protocol: TCP
        envFrom:
        - configMapRef:
            name: people-config-kubernetes
        resources: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600


